"""added users table

Revision ID: d669c77f87cc
Revises: a008a2f384db
Create Date: 2023-03-22 18:12:20.739256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd669c77f87cc'
down_revision = 'a008a2f384db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
